package com.aiimpactweekend.review.constants

import com.aiimpactweekend.review.model.Applicant

val sampleApplicant = Applicant(
    "Jennifer",
    "Chan",
    "Product Manager",
    "InvestCo.",
    4,
    "MSc Mechanical Engineering",
    "University of Exeter",
    2013,
    arrayOf("Leadership", "Critical Thinking", "Emotional Intelligence"),
    true
)

val majorityMaleFirstNames = arrayOf("James", "John", "Robert", "Michael", "William", "David", "Richard", "Joseph", "Thomas", "Charles", "Christopher", "Daniel", "Matthew", "Anthony", "Donald", "Mark", "Paul", "Steven", "Andrew", "Kenneth", "George", "Joshua", "Kevin", "Brian", "Edward", "Ronald", "Timothy", "Jason", "Jeffrey", "Ryan", "Jacob", "Gary", "Nicholas", "Eric", "Stephen", "Jonathan", "Larry", "Justin", "Scott", "Brandon", "Frank", "Benjamin", "Gregory", "Raymond", "Samuel", "Patrick", "Alexander", "Jack", "Dennis", "Jerry", "Tyler", "Aaron", "Henry", "Jose", "Douglas", "Peter", "Adam", "Nathan", "Zachary", "Walter", "Kyle", "Harold", "Carl", "Jeremy", "Gerald", "Keith", "Roger", "Arthur", "Terry", "Lawrence", "Sean", "Christian", "Ethan", "Austin", "Joe", "Albert", "Jesse", "Willie", "Billy", "Bryan", "Bruce", "Noah", "Jordan", "Dylan", "Ralph", "Roy", "Alan", "Wayne", "Eugene", "Juan", "Gabriel", "Louis", "Russell", "Randy", "Vincent", "Philip", "Logan", "Bobby", "Harry")
val majorityFemaleFirstNames = arrayOf("Mary", "Patricia", "Jennifer", "Linda", "Elizabeth", "Barbara", "Susan", "Sarah", "Margaret", "Karen", "Nancy", "Lisa", "Betty", "Dorothy", "Sandra", "Ashley", "Kimberly", "Donna", "Emily", "Carol", "Michelle", "Amanda", "Melissa", "Deborah", "Stephanie", "Rebecca", "Laura", "Helen", "Sharon", "Cynthia", "Kathleen", "Amy", "Shirley", "Angela", "Anna", "Ruth", "Brenda", "Pamela", "Nicole", "Katherine", "Samantha", "Christine", "Catherine", "Virginia", "Debra", "Rachel", "Janet", "Emma", "Carolyn", "Maria", "Heather", "Diane", "Julie", "Joyce", "Evelyn", "Joan", "Victoria", "Kelly", "Christina", "Lauren", "Frances", "Martha", "Judith", "Cheryl", "Megan", "Andrea", "Olivia", "Ann", "Jean", "Alice", "Jacqueline", "Hannah", "Doris", "Kathryn", "Gloria", "Teresa", "Sara", "Janice", "Marie", "Julia", "Grace", "Judy", "Theresa", "Madison", "Beverly", "Denise", "Marilyn", "Amber", "Danielle", "Rose", "Brittany", "Diana", "Abigail", "Natalie", "Jane", "Lori", "Alexis", "Tiffany")
val majorityLastNames = arrayOf("Smith", "Johnson", "Williams", "Jones", "Brown", "Davis", "Miller", "Wilson", "Moore", "Taylor", "Anderson", "Thomas", "Jackson", "White", "Harris", "Martin", "Thompson", "Garcia", "Martinez", "Robinson", "Clark", "Rodriguez", "Lewis", "Lee", "Walker", "Hall", "Allen", "Young", "Hernandez", "King", "Wright", "Lopez", "Hill", "Scott", "Green", "Adams", "Baker", "Gonzalez", "Nelson", "Carter", "Mitchell", "Perez", "Roberts", "Turner", "Phillips", "Campbell", "Parker", "Evans", "Edwards", "Collins", "Stewart", "Sanchez", "Morris", "Rogers", "Reed", "Cook", "Morgan", "Bell", "Murphy", "Bailey", "Rivera", "Cooper", "Richardson", "Cox", "Howard", "Ward", "Torres", "Peterson", "Gray", "Ramirez", "James", "Watson", "Brooks", "Kelly", "Sanders", "Price", "Bennett", "Wood", "Barnes", "Ross", "Henderson", "Coleman", "Jenkins", "Perry", "Powell", "Long", "Patterson", "Hughes", "Flores", "Washington", "Butler", "Simmons", "Foster", "Gonzales", "Bryant ", "Alexander", "Russell", "Griffin ", "Diaz", "Hayes")
val workPositions = arrayOf("Marketing Manager", "Marketing Communications Manager", "Product Manager", "Brand Manager", "SEO Manager", "Content Marketing Manager", "Digital Marketing Manager", "Branch Manager", "Business Manager", "Office Manager", "Administrative Manager", "Risk Manager", "Program Manager", "Manager", "Assistant Manager", "IT Manager", "Sales Manager", "Store Manager", "Sales Manager", "Store Manager", "Account Manager", "Area Sales Manager", "Outside Sales Manager", "Market Development Manager", "Managers", "Office Manager", "Customer Service Manager", "Operations Manager", "Benefits Manager", "Finance Manager")
val companyNames = arrayOf("Finance", "Bank", "Business", "Econs", "Invest", "Blockchain", "AI", "Info", "Data")
val companyTypes = arrayOf("Co.", "Ltd.", "Plc.", "Corp")
val degreeNames = arrayOf("BA in Architecture", "BA in Clinical Science", "BA in Commerce", "BA in Community Health", "BA in Criminal Justice", "BA in Divinity", "BA in Economics", "BA in Education", "BA in Engineering", "BA in Fine Arts", "BA in Letters", "BA in Management", "BA in Music", "BA in Pharmacy", "BA in Philosophy", "BA in Social Work", "BA in Technology", "BA in Accountancy", "BA in Arts in Biology", "BSc in Actuarial", "BSc in Agriculture", "BSc in Architecture", "BSc in Biology", "BSc in Chemistry", "BSc in Criminology", "BSc in Education", "BSc in Food Science", "BSc in Foreign Service", "BSc in Forestry", "BSc in History", "BSc in Journalism", "BSc in Management", "BSc in Marketing", "BSc in Mathematics", "BSc in Meteorology", "BSc in Microbiology", "BSc in Neuroscience", "BSc in Nursing", "BSc in Podiatry", "BSc in Pharmacology", "BSc in Pharmacy", "BSc in Physics", "BSc in Plant Science", "BSc in Politics", "BSc in Psychology", "BSc in Public Safety", "BSc in Physiology")
val allTraits = arrayOf("Public Speaking", "Leadership", "Work Ethic", "Critical Thinking", "Sales", "Marketing", "Flexibility", "Adaptibility", "Interpersonal Skills", "Problem Solving", "Project Management", "Emotional Intelligence", "Conflict Resolution", "Negotiation")
val englishCities = arrayOf("London", "Manchester", "Yorkshire", "Newcastle", "Liverpool", "Birmingham", "Leeds", "Sheffield", "Bristol", "Leicester")